application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "very-strong-secret-1234-that-is-long-enough-i-hope-very-much-please-be-long-enough"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "postgres"
  require_ssl: false
redis_uri: "redis://127.0.0.1:6379"