name: Automated Deployment

on:
  push:
    branches: [ main ]
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and push to Docker
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build images
        working-directory: ./web
        run: |
          # docker build --tag clockwork-server ./server
          docker build --tag clockwork-balancer ./nginx
          # docker tag clockwork-server jangryga/clockwork-server:latest
          docker tag clockwork-balancer jangryga/clockwork-balancer:latest
          # docker push jangryga/clockwork-server
          docker push jangryga/clockwork-balancer
  
  deploy:
    name: Deploy to Linode
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add the private SSH key to the ssh-agent
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
      - name: Build and deploy images on Linode
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          scp  -o StrictHostKeyChecking=no -r ./web/docker-compose.yaml root@${{ secrets.LINODE_IP_ADDRESS }}:/app
          ssh -o StrictHostKeyChecking=no root@${{ secrets.LINODE_IP_ADDRESS }} << 'ENDSSH'
            cd /app
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker compose pull 
            docker compose up -d
          ENDSSH