name: Automated Deployment

on:
  push:
    branches: [main]
    paths:
      - "server"
  workflow_dispatch:

jobs:
  docker-build:
    name: Build server
    runs-on: ubuntu-22.04
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      # - name: Set environment variables
      #   run: |
      #     echo "WEB_IMAGE=$(echo ${{env.SERVER_IMAGE}} )" >> $GITHUB_ENV
      #     echo "NGINX_IMAGE=$(echo ${{env.NGINX_IMAGE}} )" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build images
        working-directory: ./web/server
        run: |
          docker build --tag clockwork-server .
          docker tag clockwork-server jangryga/clockwork-server:latest
          docker push jangryga/clockwork-server
