name: Automated Deployment

on:
  push:
    branches: [ main ]
    paths:
      - "web"
  workflow_dispatch:

jobs:
  build:
    name: Build and push to Docker
    runs-on: ubuntu-22.04

    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build images
        working-directory: ./web/server
        run: |
          docker build --tag clockwork-server .
          docker tag clockwork-server jangryga/clockwork-server:latest
          docker push jangryga/clockwork-server
  
  deploy:
    name: Deploy to Linode
    runs-on: ubuntu-22.04
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Log in
        run: echo "hello world"