version: "3.8"

services:
  web:
    image: jangryga/clockwork-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info

  nginx:
    image: jangryga/clockwork-balancer:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/skillstech.app:/var/www/skillstech.app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
