version: "3.8"

services:
  web:
    image: jangryga/clockwork-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - APP_APPLICATION__BASE_URL="https://skillstech.app"
      - APP_DATABASE__HOST=${DB_HOST}
      - APP_DATABASE__USERNAME=${DB_USERNAME}
      - APP_DATABASE__PASSWORD=${DB_PASSWORD}
      - APP_DATABASE__DATABASE_NAM=${DB_DATABASE_NAME}
    depends_on:
      - redis
  
  redis:
    image: redis:7
    volumes:
      - redis_data:/data

  nginx:
    image: jangryga/clockwork-balancer:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/skillstech.app:/var/www/skillstech.app
      - /var/www/static:/var/www/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

  downloader:
    image: jangryga/salad-downloader:0.0.2
    ports: 
      - "8081:8080"

volumes:
  redis_data: