version: "3.8"

services:
  web:
    image: jangryga/clockwork-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - RUST_BACKTRACE=1
      - APP_APPLICATION__BASE_URL="https://skillstech.app"
      
    depends_on:
      - redis
  
  redis:
    image: redis:7
    volumes:
      - redis_data:/data


  nginx:
    image: jangryga/clockwork-balancer:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/skillstech.app:/var/www/skillstech.app
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  redis_data: